FROM pypy:2

# Install the necessary packages:
RUN pip install Django psycopg2cffi Pillow pytz gunicorn
 
# Create the directory that will contain application's source files:
WORKDIR /usr/local/share/cmbarter
COPY cmbarter cmbarter/
COPY doc doc/
COPY static static/

# The volume that will contain django's session files:
VOLUME /var/tmp/cmbarter

EXPOSE 8000
CMD ["gunicorn", "-b :8000", "--log-level=warning", "--access-logfile=-", "--error-logfile=-", "cmbarter.wsgi"]
