FROM debian:latest

# Install the necessary packages:
RUN apt-get update && apt-get install -y \
    python-django \
    python-psycopg2 \
    python-imaging \
    python-crypto \
    python-tz \
    gunicorn \
 && rm -rf /var/lib/apt/lists/*
 
# Create the directory that will contain application's source files:
WORKDIR /usr/local/share/cmbarter
COPY cmbarter cmbarter/
COPY doc doc/
COPY static static/

# The volume that will contain django's session files:
VOLUME /var/tmp/cmbarter

EXPOSE 8000
CMD ["gunicorn", "-b :8000", "--log-level=warning", "--access-logfile=-", "--error-logfile=-", "cmbarter.wsgi"]
