FROM pypy:2

# Install the necessary packages:
RUN pip install Django~=1.11 psycopg2cffi Pillow pytz gunicorn
 
# Copy the files we need:
COPY cmbarter /usr/local/share/cmbarter/cmbarter/
COPY doc /usr/local/share/cmbarter/doc/
COPY static /usr/local/share/cmbarter/static/

CMD ["gunicorn", "-b :8000", "--log-level=warning", "--access-logfile=-", "--error-logfile=-", "cmbarter.wsgi"]

EXPOSE 8000

ENV PYTHONPATH /usr/local/share/cmbarter

################################################################################

# Set this to the number of worker processes for handling requests --
# a positive integer generally in the 2-4 * $NUM_CORES range. You may
# want to vary this a bit to find the best for your particular
# workload.
ENV WEB_CONCURRENCY 1

# Set this to your site domain name.
ENV CMBARTER_HOST localhost

# Set this to the PostgreSQL database connection string.
ENV CMBARTER_DSN host=db dbname=cmbarter user=postgres password=mysecretpassword

# Make this long and unique, and don't share it with anybody.
ENV CMBARTER_SECRET_KEY vjgz%^^7f6-=#%f&5y8qw2ous-l6zz!h+rkpzmxx(ozp%^xeb)

# This should point to a page telling more about the site.
ENV CMBARTER_ABOUT_US_URL https://sourceforge.net/projects/cmb/

# This should be "False" in production.
ENV CMBARTER_DEBUG_MODE False

# Sign-up and log-in settings:
ENV CMBARTER_MIN_PASSWORD_LENGTH 8
ENV CMBARTER_SHOW_CAPTCHA_ON_SIGNUP True
ENV CMBARTER_SHOW_CAPTCHA_ON_REPETITIVE_LOGIN_FAILURE True
ENV CMBARTER_REGISTRATION_KEY_IS_REQUIRED False
ENV CMBARTER_REGISTRATION_KEY_PREFIX=

# By default, CMB is configured to show CAPTHCA on sign-up, and after
# five unsuccessful attempts to log-in. If you have not altered the
# default behavior, you should obtain your own public/private key pair
# from www.google.com/recaptcha, and put it here:
ENV CMBARTER_RECAPTCHA_PUBLIC_KEY 6Ledx7wSAAAAAICFw8vB-2ghpDjzGogPRi6-3FCr
ENV CMBARTER_RECAPTCHA_PIVATE_KEY 6Ledx7wSAAAAAEskQ7Mbi-oqneHDSFVUkxGitn_y

# If a registration key is required for signing up, the next setting
# should point to an URL where users will be instructed how to obtain
# a registration key.
ENV CMBARTER_REGISTRATION_KEY_HELP_URL=

# The time zone of your users. For example: Europe/Rome
ENV CMBARTER_DEFAULT_USERS_TIME_ZONE=

# Set this to a page where users can search for trusted partners.
ENV CMBARTER_SEARCH_PARTNERS_URL=

# This is the maximum size in bytes for users' uploaded photographs.
ENV CMBARTER_MAX_IMAGE_SIZE 716800

# This is the maximum amount of pixels (width * height) in users'
# uploaded photographs.
ENV CMBARTER_MAX_IMAGE_PIXELS 30000000

# By default, CMB is configured to maintain a whitelist of "good" IP
# addresses. This auto-generated whitelist can be used to configure
# your firewall to protect your web-servers from DoS attacks. To be
# able to reliably determine the IP addresses of your clients, CMB
# should know the IP address(es) of all reverse proxy server(s) in
# your network. Normally, here you should substitute 'proxy' with the
# name of your reverse-proxy server.
ENV CMBARTER_REVERSE_PROXIES ip_addresses(\'proxy\')
