FROM pypy:2
ENV PYTHONPATH /usr/local/share/cmbarter

# Install the necessary packages:
RUN pip install pytz psycopg2cffi
RUN apt-get update && apt-get install -y \
    python-psycopg2 \
    python-tz \
 && rm -rf /var/lib/apt/lists/*
 
# Copy the files we need:
COPY cmbarter /usr/local/share/cmbarter/cmbarter/
COPY check_sessions.py \
     execute_turn.py \
     generate_regkeys.py \
     process_emails.py \
     schedule_turns.py \
     show_emails.py \
     show_whitelist.py \
     set_language.py \
     docker/repeat_esential_tasks.py \
     /usr/local/bin/

# The volume that will contain django's session files:
VOLUME /var/tmp/cmbarter

STOPSIGNAL SIGINT

CMD ["repeat_esential_tasks.py"]
